### ISSUE TITLE
"READ_EXTERNAL_STORAGE" and "WRITE_EXTERNAL_STORAGE" issue.

### ISSUE THREAD

**Issue by crisjonas7** [MobilePorting/FNF-PsychEngine-Base-Mobile#147]
### Describe your problem here.

I have a problem:

`source/mobile/backend/SUtil.hx:179: characters 65-86 : Class<android.Permissions> has no field READ_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:181: characters 66-87 : Class<android.Permissions> has no field READ_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:181: characters 132-153 : Class<android.Permissions> has no field READ_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:182: characters 66-88 : Class<android.Permissions> has no field WRITE_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:182: characters 133-155 : Class<android.Permissions> has no field WRITE_EXTERNAL_STORAGE `

I don't know how to solve this, so I need help.

### Are you modding a build from source or with Lua?

Lua and Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I pasted "assets" and "mod_template" from my Psych Engine 0.7.3, and "MainMenuState.hx".

**Comment by mcagabe19** [comment]
0.7.3 is obsolete

**Comment by KarimAkra** [comment]
You're using an old version or the repo source code
Either update the source code or downgrade extension-androidtools

**Comment by crisjonas7** [comment]
oh, thanks!
