### ISSUE TITLE
Tried to access a null variable FixVideo

### ISSUE THREAD

**Issue by MsterBranPlayz** [MobilePorting/FNF-PsychEngine-Base-Mobile#148]
### Describe your bug here.

Videos won’t play. (Cutscenes, etc) 

### Crash Log or logcat logs (if existing)

```bash
ERROR ON LOADING: /private/var/mobile/containers/data/application


Tried to access a null variable FixVideo
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added mods in the /Mods folder.

**Comment by mcagabe19** [comment]
what's ur psych version and iOS ver

**Comment by MsterBranPlayz** [comment]
> what's ur psych version and iOS ver



> what's ur psych version and iOS ver

0.7.3 and 17.5

**Comment by mcagabe19** [comment]
0.7.3 is obsolute and we not working on it, use devbuilds instead.

**Comment by MsterBranPlayz** [comment]
> 0.7.3 is obsolute and we not working on it, use devbuilds instead.

it still showed the same error on the devbuild

**Comment by Axe555** [comment]
same problem :/
