### ISSUE TITLE
solid black bf character

### ISSUE THREAD

**Issue by MsterBranPlayz** [MobilePorting/FNF-PsychEngine-Base-Mobile#149]
### Describe your bug here.

whenever i switch a character back to its original sprite, it turns into a solid black bf sprite, as said in the title

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not

**Comment by moxie-coder** [comment]
that’s a problem with your phone, not the game
