### ISSUE TITLE
Can’t click OK on the copy files screen

### ISSUE THREAD

**Issue by WayloFunk** [MobilePorting/FNF-PsychEngine-Base-Mobile#150]
### Describe your bug here.

I’m not able to tap on the button that says OK in the iOS version

### Crash Log or logcat logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
outdated reinstall from source
