### ISSUE TITLE
Cant add mods

### ISSUE THREAD

**Issue by Lol58117** [MobilePorting/FNF-PsychEngine-Base-Mobile#151]
### Describe your bug here.

Idk if its a bug but i cant copy mods into the mods folder

### Crash Log or logcat logs (if existing)

```bash
FNF B-Side (Redux + Classic).zip
1	Cannot create folder : /storage/emulated/0/‪Android/data/com.shadowmario.psychengine/files/mods/FNF B-Side (Redux + Classic)
2	errno=22 : Invalid argument
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
download EXTERNAL or OBB versions
