### ISSUE TITLE
VirualPad Problem

### ISSUE THREAD

**Issue by 1XxNONAMExX1** [MobilePorting/FNF-PsychEngine-Base-Mobile#154]
### Describe your problem here.

https://github.com/user-attachments/assets/fcfc3541-212b-48a2-ac73-ff06d26dfc98

### Are you modding a build from source or with Lua?

Lua and Source

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

I create a new state and try add virtualPad to it

**Comment by mcagabe19** [comment]
you may need configure vpad urself, I can't really help on that I not have the source

**Comment by 1XxNONAMExX1** [comment]
thanks anyway
