### ISSUE TITLE
Cutscene problem on 0.7.3

### ISSUE THREAD

**Issue by Crazyry2029** [MobilePorting/FNF-PsychEngine-Base-Mobile#155]
### Describe your bug here.

![Screenshot_20240723_202328](https://github.com/user-attachments/assets/98938a73-1bcd-4ac1-83eb-cb345cbfe0dd)
I downloaded a mod optimized for android (twiddlefinger) but whenever it gets to the part at the cutscene, it will spam the "ERROR ON LOADING" text for the rest of the song instead of loading the cutscene even though the version I downloaded was 0.7.3. I'm relatively new to coding and moding so I'm wondering if anyone can help out.

P.S. I've tried multiple APK's for 0.7.3 and none worked, and whenever I try and download the source code, it never tells me how much time is left and stops downloading when i try to check. Also the number after "SScript:" changes based on how many times it spammed me with the error during the song (Ex. the first time it says it is 1, then the next time is 2, then 3, 4, 5, etc.) Also I want to note that even though I get the error, it let's me continue the song, just without the cutscene.

### Crash Log or logcat logs (if existing)

```bash
ERROR ON LOADING (/storage/emulated/0/.PsychEngine/mods/twiddlefinger( Luna Accurate Style)/scripts/VideoSpriteHandler.lua): SScript: 7209: Unknown variable: good_ending
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have not

**Comment by Crazyry2029** [comment]
nvm, I just found a better mod

**Comment by moxie-coder** [comment]
okay
