### ISSUE TITLE
Problem with video

### ISSUE THREAD

**Issue by haeynaa** [MobilePorting/FNF-PsychEngine-Base-Mobile#156]
### Describe your problem here.

![IMG_4582](https://github.com/user-attachments/assets/9f170832-22b5-4b58-bdd9-31de127aa089)

im getting this error, type not found, i may know that maybe the problem is that in the source doesn't have this?

`import psychlua.LuaUtils;

import hxcodec.flixel.FlxVideo;

var globalData:Array<Array> = [];

createGlobalCallback('makeVideoSprite', function(tag:String, videoFile:String, ?x:Float, ?y:Float, ?camera:String, ?shouldLoop:Bool)
{
var videoData:Array = [];

if (game.modchartSprites.exists(tag + '_video'))
{
	debugPrint('makeVideoSprite: This tag is not available! Use a different tag.', FlxColor.RED);
	return;
}

if (!FileSystem.exists(Paths.video(videoFile)))
{
	debugPrint('makeVideoSprite: The video file "' + videoFile + '" cannot be found!', FlxColor.RED);
	return;
}

var sprite:FlxSprite = new FlxSprite(x, y).makeGraphic(1, 1, FlxColor.TRANSPARENT);
sprite.camera = LuaUtils.cameraFromString(camera);
game.modchartSprites.set(tag + '_video', sprite);
add(sprite);

var video:FlxVideo = new FlxVideo();

video.alpha = 0;

video.onTextureSetup.add(function()
{
	sprite.loadGraphic(video.bitmapData);
});

video.play(Paths.video(videoFile), shouldLoop);

video.onEndReached.add(function()
{
	video.dispose();
	
	if (FlxG.game.contains(video))
		FlxG.game.removeChild(video);
	
	if (globalData.indexOf(videoData) >= 0)
		globalData.remove(videoData);
	
	if (game.modchartSprites.exists(tag + '_video'))
	{
		game.modchartSprites.get(tag + '_video').destroy();
		game.modchartSprites.remove(tag + '_video');
	}
		
	game.callOnLuas('onVideoFinished', [tag]);
	
	return;
}, true);

FlxG.game.addChild(video);

videoData.push(video);
videoData.push(sprite);

globalData.push(videoData);
});

function onPause()
{
for (video in globalData)
{
if (video[0] != null)
{
video[0].pause();

		if (FlxG.autoPause)
		{
			if (FlxG.signals.focusGained.has(video[0].resume))
				FlxG.signals.focusGained.remove(video[0].resume);

			if (FlxG.signals.focusLost.has(video[0].pause))
				FlxG.signals.focusLost.remove(video[0].pause);
		}
	}
}
}

function onResume()
{
for (video in globalData)
{
if (video[0] != null)
video[0].resume();

	if (FlxG.autoPause)
	{
		if (!FlxG.signals.focusGained.has(video[0].resume))
			FlxG.signals.focusGained.add(video[0].resume);

		if (!FlxG.signals.focusLost.has(video[0].pause))
			FlxG.signals.focusLost.add(video[0].pause);
	}
}
}

function onDestroy()
{
for (video in globalData)
{
if (video[0] != null)
video[0].stop();
}
}

var cache:Array = ['open','SO_STAY_FINAL'];

function precacheVideos()
{
for (i in 0 ... cache.length)
{
var video:FlxVideo = new FlxVideo();
video.play(Paths.video(cache[i]));
video.stop();
}
}

precacheVideos();`

that is the code  VideoSpriteHandler.hx

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by moxie-coder** [comment]
we are using hxvlc, not hxCodec https://github.com/MAJigsaw77/hxvlc

**Comment by haeynaa** [comment]
even changing to hxvlc.flixel.FlxVideo; i get the same error but of this one

**Comment by moxie-coder** [comment]
we already have our own video handler, why are you trying to make your own??

**Comment by haeynaa** [comment]
wdym we alr have?

**Comment by moxie-coder** [comment]
> wdym we alr have?

nevermind, we used to, but you can do `startVideo` to play a video cutscene

**Comment by haeynaa** [comment]
oh really, i though i had to make all by 0, thanks then moxie

**Comment by moxie-coder** [comment]
no problem
