### ISSUE TITLE
Issue making chart editor unusable

### ISSUE THREAD

**Issue by PS-hub-alt** [MobilePorting/FNF-PsychEngine-Base-Mobile#160]
### Describe your bug here.

When I use the keyboard onscreen I can’t make it go resulting in the chart unusable when trying to change a name of a song in chart editor. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
that's a won't fix but editors will be re-ported so maybe u can try ur luck after that
