### ISSUE TITLE
Error: Could not find include file "C:/haxelib/linc_luajit/git/project/Build.xml"

### ISSUE THREAD

**Issue by longge90** [MobilePorting/FNF-PsychEngine-Base-Mobile#162]
### Describe your problem here.

I installed those libraries normally, but somehow I couldn't compile them

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux, Windows or Mac)

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

extension-androidtools: [git] flixel-addons: [3.2.2] flixel: [5.6.1] funkin.vis: [git] hxcpp: [4.3.2] git hxvlc: [git] linc_luajit: [git] openfl: [9.3.3] 9.3.4 SScript: [git] tink_core: [1.26.0] tjson: [1.4.0]

**Comment by mcagabe19** [comment]
u need give the error

**Comment by longge90** [comment]
> u need give the error
Error: Could not find include file "C:/haxelib/linc_luajit/git/project/Build.xml"

**Comment by mcagabe19** [comment]
delete your global linc_luajit
