### ISSUE TITLE
Error: Could not find haxelib "linc_luajit", does it need to be installed?

### ISSUE THREAD

**Issue by longge90** [MobilePorting/FNF-PsychEngine-Base-Mobile#163]
### Describe your problem here.

PS D:\Users\FNF-PsychEngine-Base-Mobile-main> lime build android
Error: Could not find haxelib "linc_luajit", does it need to be installed?
PS D:\Users\FNF-PsychEngine-Base-Mobile-main> haxelib list      
extension-androidtools: [git]
flixel-addons: [3.2.2]       
flixel-tools: [1.5.1]        
flixel: [5.6.1]
flxanimate: [git]
funkin.vis: [git]
grig.audio: [git]
hxcpp: [4.3.2] git
hxdiscord_rpc: [git]
hxvlc: [git]
lime: [8.1.3]
linc_luajit: [1.0.3]
openfl: [9.3.3] 9.3.4
SScript: [git]
tink_core: [1.26.0]
tjson: [1.4.0]

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Which psych engine version you're on?

DevBuild

**Comment by moxie-coder** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`
