### ISSUE TITLE
System Dialogue Box Softlocks

### ISSUE THREAD

**Issue by potatex2** [MobilePorting/FNF-PsychEngine-Base-Mobile#168]
### Describe your bug here.

Using anything related to
```lua
function onCreate()
  addHaxeLibrary(‘Lib’, ‘openfl’)
end
function onCreatePost()
  runHaxeCode([[Lib.application.window.alert(‘whatever message’, ‘whatever title’]])
end
```
softlocks the game, and you can’t interact with the OK button when it shows after reopening the app from the Home Screen.

### Crash Log or logcat logs (if existing)

```bash
N/A
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A

**Comment by mcagabe19** [comment]
are u sure it's 0.7.3? if so we don't maintain sorry

**Comment by potatex2** [comment]
Fair enough 👍

**Comment by mcagabe19** [comment]
@potatex2 actually wait it's a known lime issue sorry again
