### ISSUE TITLE
compliting error

### ISSUE THREAD

**Issue by MZDM-B** [MobilePorting/FNF-PsychEngine-Base-Mobile#169]
### Describe your problem here.

i'm tring to complite this ,but it prompts these errors
I have already tried to change the version of "extension-androidtools",but the problen still exists

![d2f1d67c24045deb85e88ffc4e2f8820](https://github.com/user-attachments/assets/d2a34352-4d4e-4c37-a51f-e801e7d0c8a1)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tposejank** [comment]
Get commit hash 1432270ff689e9656a5d5d28980c44cf5c1ab2c8
