### ISSUE TITLE
runHaxeCode and hscripts doesn't work properly

### ISSUE THREAD

**Issue by MadLuck-20** [MobilePorting/FNF-PsychEngine-Base-Mobile#171]
### Describe your bug here.

many things with runHaxeCode or hxscripts do not work in 1.0 when in 0.7.3 they worked correctly

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits done

**Comment by mcagabe19** [comment]
ShadowMario updated SScript version so ¯\_(ツ)_/¯
