### ISSUE TITLE
How no zip

### ISSUE THREAD

**Issue by Frogz1112** [MobilePorting/FNF-PsychEngine-Base-Mobile#172]
### Describe your problem here.

I get no zip

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux, Windows or Mac)

### Which psych engine version you're on?

DevBuild

**Comment by moxie-coder** [comment]
https://github.com/user-attachments/assets/f01e459c-7305-4951-92a7-f5d043a99daf
