### ISSUE TITLE
vs nothing

### ISSUE THREAD

**Issue by ilikefnfmobile** [MobilePorting/FNF-PsychEngine-Base-Mobile#173]
### Describe your bug here.

tried running the killshot mod on 1.0 pre-release
it was still playable but there was nothing,just a black screen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by moxie-coder** [comment]
this feels more like a you problem if anything

**Comment by moxie-coder** [comment]
and a problem with the mod

**Comment by mcagabe19** [comment]
SScript died and SM switched to hscript-iris that still wip so
