### ISSUE TITLE
 Error sdl help

### ISSUE THREAD

**Issue by LBtrend** [MobilePorting/FNF-PsychEngine-Base-Mobile#174]
### Describe your problem here.

It helps but it really helps, how they did to solve the "SDL ERROR" is like hell but it helps

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by mcagabe19** [comment]
0.7.3 is outdated
