### ISSUE TITLE
(1.0 pre-release issue) MP4 not playing, is E-Sign installation method not working for mid-song videos? 

### ISSUE THREAD

**Issue by softbf395** [MobilePorting/FNF-PsychEngine-Base-Mobile#175]
### Describe your bug here.

Mid-song MP4’s not playing, is E-Sign (ipa signing tool) incompatible?
![IMG_3626](https://github.com/user-attachments/assets/bf7980ab-1138-4798-8d04-ed381cb233ff)
Yeah, logs not helping :/ I most likely didn’t use a compatible installation method, if there’s a correct one, please let me know which installation method is best for the iOS build!

### Crash Log or logcat logs (if existing)

```bash
assets/fonts/pixel-latin.ttf (
Called from haxe.io.Output.write (/Users/runner/hostedtoolcache/haxe/4.3.6/arm64/std/haxe/io/Output.hx line 104)
Called from sys.io.File.saveBytes (/Users/runner/hostedtoolcache/haxe/4.3.6/arm64/std/cpp/_std/sys/io/File.hx line 46))

Yeah, it’s logs are bugged for the installation method I used (E-Sign method)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed

**Comment by softbf395** [comment]
The mod is for psych engine 0.7.3 or higher

**Comment by mcagabe19** [comment]
well if it can't enable JIT idk if luajit would work

**Comment by softbf395** [comment]
I had to switch from VideoSpriteHandler.hx to its varient called VideoSpriteHandler.lua, it worked!

**Comment by softbf395** [comment]
Mod:twiddlefinger but mod folder (replaced videohandler.hx with videohandler.lua
![IMG_3630](https://github.com/user-attachments/assets/7d8a5b84-b0be-4985-bbe4-39557fcb3be1)
And yes, this is a screenshot from 1.0 (pre-release) iOS build downloaded with E-Sign

**Comment by softbf395** [comment]
Idk why the cursor was on the nugget it’s meant to stop showing the cursor before the cutscene

**Comment by softbf395** [comment]
> well if it can't enable JIT idk if luajit would work

I found a lua version of VideoHandler.hx, it worked!
