### ISSUE TITLE
psych engine errors on android 

### ISSUE THREAD

**Issue by Trodsus** [MobilePorting/FNF-PsychEngine-Base-Mobile#177]
### Describe your bug here.

1.the error just pops up for no reason 2. the chart editor is terrible you have to enter the name and not just scroll on the screen on the phone 3. too many lives are taken away I can't play the song like that 4. you have to go into the data folder which is bad because earlier on the 7.3.0 engine it was in the strage folder. these bugs on an android phone and this is very bad I know this is a pre-release but there are still a lot of bugs 

### Crash Log or logcat logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Trodsus** [comment]
very bad even for a pre-release on a phone

**Comment by mcagabe19** [comment]
1. what error
2. due upstream change we limited to only to names
3. what
4. Options > Mobile Options > Change Storage Type

**Comment by mcagabe19** [comment]
closing due nosense
