### ISSUE TITLE
Character Editor text boxes? (iOS)

### ISSUE THREAD

**Issue by WayloFunk** [MobilePorting/FNF-PsychEngine-Base-Mobile#179]
### What is your question?

Why cant I remove the the virtual keyboard? I can’t interact with any of the GUI due to the keyboard being in the way after typing.

**Comment by mcagabe19** [comment]
that's a wontfix since we don't own any iOS device

**Comment by WayloFunk** [comment]
💀

**Comment by WayloFunk** [comment]
Why don’t you add a custom keyboard widget that closes the on screen keyboard like TeamViewer

**Comment by moxie-coder** [comment]
> Why don’t you add a custom keyboard widget that closes the on screen keyboard like TeamViewer

because that was made by apple, and I’m pretty sure that’s not possible without knowing the api for it, since I’m pretty sure only apple can only do that, but I’m not sure
