### ISSUE TITLE
Can’t load cutcenes mid-son with lua

### ISSUE THREAD

**Issue by DaniTrox** [MobilePorting/FNF-PsychEngine-Base-Mobile#180]
### Describe your bug here.

It can’t load cutscenes mid-song, like Twiddlefinger

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a Psych engine Lua port

**Comment by mcagabe19** [comment]
0.7.3 is outdated
