### ISSUE TITLE
Ingame music stops when iOS interrupts it

### ISSUE THREAD

**Issue by WayloFunk** [MobilePorting/FNF-PsychEngine-Base-Mobile#181]
### Describe your bug here.

The music in the game stops when someone calls or system audio (Like alarms) silents the music and the notes don’t move anymore.

### Crash Log or logcat logs (if existing)

```bash
Nah
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
lime openal releated issue reopening game always fixes it
