### ISSUE TITLE
Unable to add custom stage

### ISSUE THREAD

**Issue by TwisBbbb** [MobilePorting/FNF-PsychEngine-Base-Mobile#183]
### Describe your bug here.

I can't add a custom stage. I added .lua and .json, but in the stage, it doesn't show up https://youtu.be/EA3VZcweEoo?si=l2UtQSZcBAB5S_eW

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
you wrote `OnCreate`, it's `onCreate`

**Comment by TwisBbbb** [comment]
Thanks 🙏
