### ISSUE TITLE
The iOS Version is basically unmoddable.

### ISSUE THREAD

**Issue by RandomGuy-e** [MobilePorting/FNF-PsychEngine-Base-Mobile#185]
### Describe your problem here.

When I type something in one of the boxes. I can’t exit out of the keyboard.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn’t edit anything.

**Comment by RandomGuy-e** [comment]
Edit: I think i now know what the lua or source thing means so actually i think im doing it from source

**Comment by mcagabe19** [comment]
hold and slowly swipe ur home island and open psych again

**Comment by WayloFunk** [comment]
iPhone 13 users: 💀
