### ISSUE TITLE
How to delete original game files safely in Android version 1.0

### ISSUE THREAD

**Issue by nguyenkiet1234d** [MobilePorting/FNF-PsychEngine-Base-Mobile#187]
### What is your question?

I want to create a large mod in the original game file and I will need to delete unnecessary things in the mod and still be safe, what should I do?

**Comment by mcagabe19** [comment]
remove `BASE_GAME_FILES` define on Project.xml and compile

**Comment by nguyenkiet1234d** [comment]
> xóa `BASE_GAME_FILES`định nghĩa trên Project.xml và biên dịch

Sorry, but after deleting, where should I put that file?

**Comment by moxie-coder** [comment]
> > xóa `BASE_GAME_FILES`định nghĩa trên Project.xml và biên dịch
> 
> Sorry, but after deleting, where should I put that file?

you just need to delete it from project.xml

**Comment by nguyenkiet1234d** [comment]
but I can't find it in the game apk file I extracted, I really hope you can help me 

> > > xóa `BASE_GAME_FILES`định nghĩa trên Project.xml và biên dịch
> > 
> > 
> > Sorry, but after deleting, where should I put that file?
> 
> you just need to delete it from project.xml

but I can't find it in the game apk file I extracted, I really hope you can help me

**Comment by tposejank** [comment]
You cannot remove files from the original package or it WILL break
