### ISSUE TITLE
Black Texture

### ISSUE THREAD

**Issue by UnknownJohn78** [MobilePorting/FNF-PsychEngine-Base-Mobile#188]
### Describe your problem here.

The texture of girlfriend is just black IDK how to fix this...

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

No...

**Comment by mcagabe19** [comment]
ram issue plus outdated
