### ISSUE TITLE
Help with the full screen, the 1280×720 screen does not appear, the full screen appears, that is, the entire mobile

### ISSUE THREAD

**Issue by LBtrend** [MobilePorting/FNF-PsychEngine-Base-Mobile#189]
### Describe your problem here.

the title

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

Basically it is another port but it is a help as they did

**Comment by moxie-coder** [comment]
it’s meant to be full screen, wtf do you mean

**Comment by mcagabe19** [comment]
![image](https://github.com/user-attachments/assets/f986abb8-a18e-4215-bdfe-5069e0419ff7)

**Comment by moxie-coder** [comment]
fucking idiot
