### ISSUE TITLE
Unable to save note splash JSON file in The Editor And there are missing options in the Chart editor

### ISSUE THREAD

**Issue by JuanSebas1247** [MobilePorting/FNF-PsychEngine-Base-Mobile#190]
### Describe your bug here.

It won't let me save the file Note splash and some chart editor options are missing

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
chart editor is unfinished, so is note splash editor

**Comment by mcagabe19** [comment]
1. please send a vid that u're trying to save
2. chart editor is limited due mobile compatibility

**Comment by JuanSebas1247** [comment]
Well, even if I modified the normal note splash it doesn't look like something is missing, I'll show you later

**Comment by JuanSebas1247** [comment]
https://github.com/user-attachments/assets/cadc47e6-f375-41e4-b5e5-12aa5fa80d95

**Comment by mcagabe19** [comment]
![image](https://github.com/user-attachments/assets/fd9564b7-ec5d-410f-a826-88fce4e11fd5)
confirmed
