### ISSUE TITLE
The game crashes

### ISSUE THREAD

**Issue by TopedGames** [MobilePorting/FNF-PsychEngine-Base-Mobile#192]
### Describe your bug here.

Downloaded, launched, gave permission, crashed, launched, crashed.It just won't start. I tried assets and mods, both in data and in external.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Other/Unknown/I don't know

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

Нет

**Comment by mcagabe19** [comment]
you did not give info about your OS and version

**Comment by TopedGames** [comment]
OS: Android
Model: RealmeC2
Architecture: aarch64
Version Android: 9
RAM: 3
CPU cores: 8

Anything else? If necessary, tell me, I will clarify.

**Comment by mcagabe19** [comment]
`extension-androidtools` releated issue, needs to fix

**Comment by mcagabe19** [comment]
should be fixed now redownload

**Comment by TopedGames** [comment]
And how to fix it?
Also a video about the problem:

https://github.com/user-attachments/assets/a7aa1026-916b-4903-8294-59addf3740fa

**Comment by moxie-coder** [comment]
> And how to fix it? Also a video about the problem:
> 
>  XRecorder_08092024_200807_changed.mp4

Redownload the apk

**Comment by TopedGames** [comment]
I've tried it many times.

**Comment by TopedGames** [comment]
Но ошибка было в игре, её уже исправили

**Comment by moxie-coder** [comment]
okay
