### ISSUE TITLE
This is back

### ISSUE THREAD

**Issue by WayloFunk** [MobilePorting/FNF-PsychEngine-Base-Mobile#194]
### Describe your bug here.

The Press Ok to begin is back as of the latest dev build on iOS
![IMG_0891](https://github.com/user-attachments/assets/30ac1239-4017-4f45-8457-8a40d3d8b53f)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by WayloFunk** [comment]
Damn that was fast

**Comment by WayloFunk** [comment]
Wtf

**Comment by TopedGames** [comment]
Здесь нет ошибок, по моему ошибку сделали вы.
