### ISSUE TITLE
Most shaders doesn't work on mobile

### ISSUE THREAD

**Issue by lib-fluff-so** [MobilePorting/FNF-PsychEngine-Base-Mobile#199]
### Describe your bug here.

Every time when I try to open song with shaders I get this message. This happens with almost every shader that works on PC. I use Android 14. 
![photo_2024-09-10_14-29-43](https://github.com/user-attachments/assets/2b2ef7ed-c21d-48da-8f16-56e0e7c454c0)
![photo_2024-09-10_14-29-41](https://github.com/user-attachments/assets/50aa98b0-8578-4901-a34f-73362fb93252)

### Crash Log or logcat logs (if existing)

```bash
Nope, but the error message is on image.
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by mcagabe19** [comment]
you have to fix the shader yourself

**Comment by lib-fluff-so** [comment]
Oh, shoot, I think I found the problem. Thanks
