### ISSUE TITLE
Can’t install on ios

### ISSUE THREAD

**Issue by RANDOOMY** [MobilePorting/FNF-PsychEngine-Base-Mobile#201]
### Describe your problem here.

I tried to rename the .zip file with .ipa but (obviously) it didn’t work. Can someone please tell me how to install it?

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Which psych engine version you're on?

DevBuild

**Comment by tposejank** [comment]
you extract it.,.

**Comment by mcagabe19** [comment]
and use a pc with altstore and trolllstore
