### ISSUE TITLE
External files

### ISSUE THREAD

**Issue by Pikaro123** [MobilePorting/FNF-PsychEngine-Base-Mobile#204]
### Describe your problem here.

Everyone who has Android 14 cannot modify, move or change any file in android/data/. and this does not allow adding mods to the game, modifying it or moving files within it. Honestly, I think there should be an external version of the port along with the files, since we cannot modify the files. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

**Comment by Pikaro123** [comment]
@

**Comment by mcagabe19** [comment]
options > mobile options > storage type

**Comment by Stefan2008Git** [comment]
> ### Describe your problem here.
> Everyone who has Android 14 cannot modify, move or change any file in android/data/. and this does not allow adding mods to the game, modifying it or moving files within it. Honestly, I think there should be an external version of the port along with the files, since we cannot modify the files.
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Android
> 
> ### Which psych engine version you're on?
> 1.0 (Prerelease)
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

Until if you have root enabled on you device via Magisk, but needs bootloader unlocked on your phone
