### ISSUE TITLE
You Can't select a Character in Chart o Character Editor

### ISSUE THREAD

**Issue by ArngMods93** [MobilePorting/FNF-PsychEngine-Base-Mobile#205]
###I Can't scroll up or down in Chart or Character Editor 

I Can't scroll up or down to Select a Character in Chart or Character Editor

https://github.com/user-attachments/assets/19f67ee2-92a8-476f-b1e7-01fbd6509b80

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

Pre-Release 

### Did you edit anything in this build? If so, mention or summarize your changes.

Do not edit or add a New Configuration

**Comment by mcagabe19** [comment]
hold in down button or search with typing
